platform: linux

image_resource:
  type: registry-image
  source:
    repository: keppel.eu-de-1.cloud.sap/ccloud/juno-assets-server-ci-helper
    tag: "latest"

inputs:
  - name: input

params:
  CONTAINER:
  OPTIONS:
  TARGET: ""
  OVERWRITE: "false"
  OS_USERNAME: concourse
  OS_PASSWORD: ((keystone-user-password/concourse-eu-de-1))
  OS_AUTH_URL: https://identity-3.eu-de-1.cloud.sap/v3
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: master

run:
  path: /bin/bash
  args:
    - -c
    - |
      set -e
      eval "$(swift auth)"

      if [ "${OVERWRITE}" == "true" ]; then
        files=$(ls -A input/)
        for file in $files; do
          PREFIX=$(echo "${file}" | cut -d'/' -f1)
          if [ -n "${TARGET}" ]; then
            PREFIX="${TARGET}/${PREFIX}"
          fi
          swift delete "${CONTAINER}" --prefix "${PREFIX}"
        done      
      fi

      # create a subfolder if Target not empty
      if [ -n "${TARGET}" ]; then
        mkdir -p "/tmp/input/${TARGET}"
        cp -r input/* "/tmp/input/${TARGET}/"
        cd "/tmp/input"
      else
        cd input  
      fi

      swift upload "${CONTAINER}" .
