platform: linux

image_resource:
  type: registry-image
  source:
    repository: keppel.eu-de-1.cloud.sap/ccloud/juno-assets-server-ci-helper
    tag: "latest"

inputs:
  - name: input

params:
  CONTAINER:
  OPTIONS:
  OS_USERNAME: concourse
  OS_PASSWORD: ((keystone-user-password/concourse-eu-de-1))
  OS_AUTH_URL: https://identity-3.eu-de-1.cloud.sap/v3
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: master

run:
  path: /bin/bash
  args:
    - -c
    - |
      set -e
      eval "$(swift auth)"

      cd input
      package_json_files=$(ls {apps,libs}/**/package.json)
      for package_json in $package_json_files; do
        echo "Deleting parent directory of $package_json"
        dir=$(dirname $package_json)
        swift delete "${CONTAINER}" --prefix "${dir}/"
      done

      swift upload "${CONTAINER}" .
