groups:
  - name: info
    jobs:
      - readme

jobs:
  - name: readme
    serial: true
    plan:
      - task: describe-this-pipeline
        config:
          platform: "linux"
          image_resource:
            type: docker-image
            source:
              repository: keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/alpine
              tag: latest
          run:
            path: /bin/echo
            args:
              - -e
              - '\tThis pipeline is defined at: https://github.com/sapcc/juno-assets-server/\n\n'
              - '\tManage assets-server image: https://keppel.eu-de-1.cloud.sap/ccloud/juno-assets-server\n'
              - '\tManage ci-helper image: https://keppel.eu-de-1.cloud.sap/ccloud/juno-assets-server-ci-helper\n'
